export { freeze, thaw } from 'icepick'

export * from './assign'
export * from './assocIn'
export * from './dissocIn'
export * from './getIn'
export * from './merge'
export * from './reduce'
export * from './setIn'
export * from './updateIn'
